import LocalizedStrings from 'react-native-localization';


export let strings = new LocalizedStrings({


    kk: {

        tab1: "Қызықты",
        tab2: "Каталог",
        tab3: "Ойнатқыш",
        tab4: "Кітаптарым",
        tab5: "Профиль",
        new_collection: "Жаңа жинақтар",
        now_listining: "Қазір тыңдалуда",
        together_listining: "ОСЫ КІТАППЕН БІРГЕ ТЫҢДАЛҒАНДАР",
        no_active_book: 'Сізде тыңдалымда кітап жоқ, кітап таңдаңыз.',
        active_tab: 'Белсенді',
        device_tab: "Құрылғыда",
        like_tab: "Сүйікті",
        auth: "Авторизация",
        about_book: 'КІТАП ТУРАЛЫ',
        read: 'Оқыған',
        login: "Кіру",
        login_btn: "КІРУ",
        reset_btn: "Құпия сөзді қалпына келтіріңіз",
        reset_button: "ҚАЛПЫНА КЕЛТІРУ",
        register: "Тіркеу",
        register_btn: ' ТІРКЕЛУ',
        name: "Аты",
        password: "Құпия сөз",
        re_password: "Тағы бір рет",
        reset: "Құпия сөзді қалпына келтіру",
        phone: "Телефон",
        by_phone: "телефон арқылы",
        by_email: "электрондық пошта бойынша",

        left: '',
        day: ' күн қалды',
        left1: 'Сіздің жазылымыңыздан ',

        profile: "Профиль",
        changeprofile: "Профильді өңдеу",
        navigation: "Навигация",
        history_subscript: "Жазылым тарихы",
        language: "Интерфейс тілі",
        support: "Қолдау қызметі",
        message: "Қате туралы хабарлау",
        message_et: "Сіздің хабарламаңыз",
        about: "Қосымша туралы",
        exit: "Шығу",
        send: "Жіберу",
        login_error: " Пайдаланушы аты немесе құпия сөз жарамсыз ",
        sms_error: "SMS код дұрыс емес",
        register_error_phone: "Сіздің нөміріңіз тіркелген",
        register_error_email: "Сіздің e-mail тіркелген",

        register_error: "Телефон нөмірі немесе Email тіркелген",
        delete: "Жою",
        nonow: "Қазір емес",
        free: "Тегін бастаңыз",
        next: "ЖАЛҒАСТЫРУ",
        subscript: "Жазылу",
        save: 'Сақтау',
        lang_kz: 'Қазақша',
        lang_ru: 'Орысша',
        lang_select: 'Тілді таңдаңыз',

        no_subscription: 'Сізде жазылым жоқ',
        no_active: 'белсенді емес',
        no_info: "Ақпарат жоқ",
        discount1: ' ',
        discount2: ' % жеңілдік',
        search: 'Кітап және автор бойынша іздеу',
        content: 'Мазмұны',
        share_title: 'Бөлісу',

        back: "Артқа",
        timer_start:" ",
        timer_end:"  кейін SMS ты қайта жіберіңіз.",
        sms_info:"SMS те қабылдаған 5 таңбалы санды енгізіңіз. Осы  5 таңбалы сан сіздің құпия сөзіңіз болып табылады.",
        check_nomer:"Телефон нөміріңізді тексеріңіз"
    },

    ru: {

        tab1: "Интересное",
        tab2: "Каталог",
        tab3: "Плеер",
        tab4: "Мои книги",
        tab5: "Профиль",
        // HOME 
        new_collection: "Свежие подборки",
        now_listining: "Слушают сейчас",
        together_listining: "ВМЕСТЕ С ЭТОЙ КНИГОЙ СЛУШАЮТ",
        about_book: 'О КНИГЕ',
        read: 'Читает',
        // TAB text
        no_active_book: 'У вас нет прослушанных книг, выберите книги',
        active_tab: "Активные",
        device_tab: "На устройстве",
        like_tab: "Избранное",
        auth: "Авторизация",
        login: "Вход",
        login_btn: "ВОЙТИ",
        reset_btn: "восстановить пароль",
        reset_button: "ВОССТАНОВИТЬ",
        register: "Регистрация",
        register_btn: 'ЗАРЕГИСТИРОВАТЬСЯ',
        name: "Имя",
        password: "Пароль",
        re_password: "Еще раз",
        reset: "Восстановление пароля",
        phone: "Телефон",
        by_phone: "по телефону",
        by_email: "по e-mail адресу",
        left: 'осталось ',
        left1: 'Ваша подписка осталось ',
        day: 'дней',

        profile: "Профиль",
        changeprofile: "Редактировать профиль",
        navigation: "Навигация",
        history_subscript: "История подписок",
        language: "Язык интерфейса",
        support: "Служба поддержки",
        message: "Сообщить о проблеме",
        message_et: "Ваше сообщение",
        about: "О приложении",
        exit: "Выйти",
        send: "ОТПРАВИТЬ",
        login_error: "Неправильный логин или пароль",
        sms_error: "Неправильный SMS код",
        register_error: "Телефон номер или Email уже существует",
        register_error_phone: "Телефон номер уже существует",
        register_error_email: "Email уже существует",
        delete: "Удалить",
        nonow: "Не сейчас",
        free: "Начать бесплатно",
        next: "ПРОДОЛЖИТЬ",
        subscript: "Подписка",
        save: 'Сохранить',

        lang_kz: 'Қазақша',
        lang_ru: 'На русском',
        lang_select: 'Выберите язык',
        no_active: 'не активно',
        no_subscription: 'У вас нет подписки',
        no_info: "нет данных",
        discount1: 'скидка ',
        discount2: ' %',
        search: 'Поиск по книгам и авторам',
        content: 'Содержание',
        share_title: 'Поделиться',
        back: "Назад",
        timer_start:"Через  ",
        timer_end:"  отправить SMS ещё раз.",
        sms_info:"Введите 5-значный код, который вы получите в SMS. Этот 5-значный код является вашим паролем.",
        check_nomer:"проверить номер телефона"

    },


});